title: Dr Marie Van de Sande
author: Dr Marie Van de Sande
email: mvdsande@strw.leidenuniv.nl
# social links
twitter_username: marievdsande # DO NOT include the @ character, or else the build will fail!
github_username:  MarieVdS # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage


theme: minima
minima:
  social_links:
    twitter: marievdsande
    github: MarieVdS
